name: Create GitHub Release

on:
  # Run on demand
  workflow_dispatch:

  # Run on push to main when .bumpversion.cfg version is updated
  push:
    branches:
      - main
    paths:
      - .bumpversion.cfg

jobs:
  release:
    uses: plus3it/actions-workflows/.github/workflows/release.yml@b1b7bdb32125ccb05afa36909954a75b9f2ab431
    secrets:
      release-token: ${{ secrets.GH_RELEASES_TOKEN }}
